/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * MM Admin Auth API
 * Admin panel authentication. POST /admin/auth/login sets HttpOnly session cookie; client uses withCredentials.
 * OpenAPI spec version: 1.0.0
 */

export interface AdminMeDto {
  id: number;
  email: string;
  username?: string;
  isAdmin: boolean;
}
