/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Match-movie example
 * The Match-Movie API description
 * OpenAPI spec version: 1.0
 */
import type { CreateAgeRatingDto } from './createAgeRatingDto';

export interface AgeRatingPaginationResponseDto {
  data: CreateAgeRatingDto[];
  totalItems: number;
  totalPages: number;
  page: number;
  limit: number;
}
