/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Match-movie example
 * The Match-Movie API description
 * OpenAPI spec version: 1.0
 */
import type { AgeRatingNsiControllerSendProgress200Data } from './ageRatingNsiControllerSendProgress200Data';

export type AgeRatingNsiControllerSendProgress200 = {
  data?: AgeRatingNsiControllerSendProgress200Data;
};
