/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Match-movie example
 * The Match-Movie API description
 * OpenAPI spec version: 1.0
 */

export type AwardCategoryNsiControllerGetWithPagesParams = {
/**
 * Номер страницы
 */
page?: number;
/**
 * Элементов на страницу
 */
limit?: number;
/**
 * Поиск по названию категории
 */
name?: string;
keyword?: string;
/**
 * ID родительской премии
 */
awardId?: number;
};
