/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Match-movie example
 * The Match-Movie API description
 * OpenAPI spec version: 1.0
 */
import type { AwardsNsiControllerSendProgress200Data } from './awardsNsiControllerSendProgress200Data';

export type AwardsNsiControllerSendProgress200 = {
  data?: AwardsNsiControllerSendProgress200Data;
};
