/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Match-movie example
 * The Match-Movie API description
 * OpenAPI spec version: 1.0
 */

export type ClientType = typeof ClientType[keyof typeof ClientType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClientType = {
  GOOGLE: 'GOOGLE',
  NONE: 'NONE',
} as const;
