/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Match-movie example
 * The Match-Movie API description
 * OpenAPI spec version: 1.0
 */
import type { ContentTypeNsiControllerSendProgress200Data } from './contentTypeNsiControllerSendProgress200Data';

export type ContentTypeNsiControllerSendProgress200 = {
  data?: ContentTypeNsiControllerSendProgress200Data;
};
