/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Match-movie example
 * The Match-Movie API description
 * OpenAPI spec version: 1.0
 */
import type { CountriesNsiControllerSendProgress200Data } from './countriesNsiControllerSendProgress200Data';

export type CountriesNsiControllerSendProgress200 = {
  data?: CountriesNsiControllerSendProgress200Data;
};
