/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Match-movie example
 * The Match-Movie API description
 * OpenAPI spec version: 1.0
 */
import type { ErrorResponseDtoMessage } from './errorResponseDtoMessage';

export interface ErrorResponseDto {
  /** HTTP status code */
  statusCode: number;
  /** Error message or array of error messages */
  message: ErrorResponseDtoMessage;
  /** Error type name */
  error: string;
  /** ISO timestamp when error occurred */
  timestamp: string;
  /** Request path */
  path: string;
  /** HTTP method */
  method: string;
}
