/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Match-movie example
 * The Match-Movie API description
 * OpenAPI spec version: 1.0
 */
import type { FeedbackControllerGetFeedbackMessagesStatus } from './feedbackControllerGetFeedbackMessagesStatus';

export type FeedbackControllerGetFeedbackMessagesParams = {
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * Exact match (optional)
 */
email?: string;
/**
 * Substring search in email (optional)
 */
emailQuery?: string;
status?: FeedbackControllerGetFeedbackMessagesStatus;
createdFrom?: string;
createdTo?: string;
/**
 * Sorting format: createdAt:asc|desc
 */
sort?: string;
/**
 * If true: only messages with admin reply
 */
hasReply?: boolean;
};
