/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Match-movie example
 * The Match-Movie API description
 * OpenAPI spec version: 1.0
 */
import type { FeedbackMessageResponseStatus } from './feedbackMessageResponseStatus';

export interface FeedbackMessageResponse {
  id: number;
  email: string;
  text: string;
  status: FeedbackMessageResponseStatus;
  /** @nullable */
  adminReply: string | null;
  /** @nullable */
  adminRepliedAt: string | null;
  createdAt: string;
  updatedAt: string;
}
