/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Match-movie example
 * The Match-Movie API description
 * OpenAPI spec version: 1.0
 */

export type FeedbackMessageResponseStatus = typeof FeedbackMessageResponseStatus[keyof typeof FeedbackMessageResponseStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FeedbackMessageResponseStatus = {
  NEW: 'NEW',
  IN_PROGRESS: 'IN_PROGRESS',
  ANSWERED: 'ANSWERED',
} as const;
