/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Match-movie example
 * The Match-Movie API description
 * OpenAPI spec version: 1.0
 */

export type FilterUsageAnalyticsControllerGetFilterUsageFilterType = typeof FilterUsageAnalyticsControllerGetFilterUsageFilterType[keyof typeof FilterUsageAnalyticsControllerGetFilterUsageFilterType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FilterUsageAnalyticsControllerGetFilterUsageFilterType = {
  genre: 'genre',
  exclude_genre: 'exclude_genre',
  country: 'country',
  year: 'year',
  rating: 'rating',
} as const;
