/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Match-movie example
 * The Match-Movie API description
 * OpenAPI spec version: 1.0
 */
import type { FilterUsageAnalyticsControllerGetFilterUsageFilterType } from './filterUsageAnalyticsControllerGetFilterUsageFilterType';

export type FilterUsageAnalyticsControllerGetFilterUsageParams = {
/**
 * @minimum 1
 */
page?: number;
/**
 * @minimum 1
 * @maximum 100
 */
limit?: number;
filterType?: FilterUsageAnalyticsControllerGetFilterUsageFilterType;
/**
 * selectionCount:asc or selectionCount:desc
 */
sort?: string;
};
