/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Match-movie example
 * The Match-Movie API description
 * OpenAPI spec version: 1.0
 */
import type { FilterUsageItemResponseDtoFilterType } from './filterUsageItemResponseDtoFilterType';

export interface FilterUsageItemResponseDto {
  /** Stable filter id within its type (genre id, year, etc.) */
  id: string;
  name: string;
  filterType: FilterUsageItemResponseDtoFilterType;
  selectionCount: number;
  updatedAt: string;
}
