/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Match-movie example
 * The Match-Movie API description
 * OpenAPI spec version: 1.0
 */
import type { FilterUsageItemResponseDto } from './filterUsageItemResponseDto';

export interface FilterUsagePageResponseDto {
  page: number;
  limit: number;
  total: number;
  items: FilterUsageItemResponseDto[];
}
