/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Match-movie example
 * The Match-Movie API description
 * OpenAPI spec version: 1.0
 */

export interface GetAwardCategoryByIdDto {
  id: number;
  name: string;
  slug: string;
  awardId: number;
  createdAt: string;
  updatedAt: string;
  description?: string;
  keywords: string[];
}
