/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Match-movie example
 * The Match-Movie API description
 * OpenAPI spec version: 1.0
 */

export type I18nControllerGetLandingDictionaryParams = {
/**
 * Requested locale code. Supported: en, ru, es, de, ja
 */
locale?: string;
};
