/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * MM Admin API
 * API documentation for MM Admin backend. All endpoints use JWT authentication via HTTP-only cookies or Bearer token in Authorization header.

## WebSocket Chat API

Chat functionality is available via WebSocket connections. See [WebSocket Chat Documentation](./websocket-chat.md) for details.

### Quick Reference:
- **Connection:** 
  - Development: `ws://localhost:4000/rooms`
  - Production with proxy: Use relative URL `/rooms` or `/socket.io/` (Socket.IO will auto-detect protocol)
  - Production direct: `wss://your-backend-server/rooms` (⚠️ MUST use `wss://` for HTTPS sites)
- **Important:** 
  - For HTTPS frontends (like `https://dashboard.moviematch.space`), you MUST use `wss://` protocol, not `ws://`
  - If using proxy (Next.js rewrites), use relative URL: `/rooms` or let Socket.IO auto-detect
  - Socket.IO client will automatically use `wss://` if page is loaded over HTTPS
- **Authentication:** JWT token in cookie or Authorization header
- **Events:**
  - `sendMessage` - Send a chat message
  - `chatHistory` - Receive chat history (auto-sent on room join)
  - `newMessage` - Receive new messages from other users
  - `error` - Error notifications

### Chat Message Format:
```json
{
  "roomId": "uuid",
  "message": "Your message text (1-1000 characters)"
}
```

### Requirements:
- User must be authenticated
- User must be a member of the room
- Messages are limited to 1000 characters
- Chat history is automatically sent when joining a room (up to 100 messages)

 * OpenAPI spec version: 1.0
 */

export * from './adminLoginDto';
export * from './ageRatingControllerGetInfiniteParams';
export * from './ageRatingControllerGetWithPagesParams';
export * from './ageRatingControllerSendProgress200';
export * from './ageRatingControllerSendProgress200Data';
export * from './ageRatingPaginationResponseDto';
export * from './awardCategoryControllerGetInfiniteParams';
export * from './awardCategoryControllerGetWithPagesParams';
export * from './awardCategoryControllerSendProgress200';
export * from './awardCategoryControllerSendProgress200Data';
export * from './awardPaginationResponseDto';
export * from './awardSearchParamsDto';
export * from './awardsControllerGetInfiniteParams';
export * from './awardsControllerGetWithPagesParams';
export * from './awardsControllerSendProgress200';
export * from './awardsControllerSendProgress200Data';
export * from './contentTypeControllerGetInfiniteParams';
export * from './contentTypeControllerGetWithPagesParams';
export * from './contentTypeControllerSendProgress200';
export * from './contentTypeControllerSendProgress200Data';
export * from './contentTypePaginationResponseDto';
export * from './contentTypeSearchParamsDto';
export * from './countriesControllerGetInfiniteParams';
export * from './countriesControllerGetWithPagesParams';
export * from './countriesControllerSendProgress200';
export * from './countriesControllerSendProgress200Data';
export * from './countriesPaginationResponseDto';
export * from './createAgeRatingDto';
export * from './createAwardCategoryDto';
export * from './createAwardDto';
export * from './createContentTypeDto';
export * from './createCountryDto';
export * from './createGenreDto';
export * from './createRedisUserDto';
export * from './createRoomDto';
export * from './errorResponseDto';
export * from './errorResponseDtoMessage';
export * from './fileUploadDto';
export * from './genrePaginationResponseDto';
export * from './genresControllerGetInfiniteParams';
export * from './genresControllerGetWithPagesParams';
export * from './genresControllerSendProgress200';
export * from './genresControllerSendProgress200Data';
export * from './getAgeRatingByIdDto';
export * from './getAwardByIdDto';
export * from './getAwardCategoryByIdDto';
export * from './getContentTypeByIdDto';
export * from './getCountryByIdDto';
export * from './getGenreByIdDto';
export * from './idParamDto';
export * from './joinRoomDto';
export * from './loginDto';
export * from './loginResponseDto';
export * from './redisUserResponseDto';
export * from './redisUserResponseDtoRole';
export * from './roomMembersResponseDto';
export * from './roomMembersResponseDtoMembersItem';
export * from './roomMembersResponseDtoMembersItemRole';
export * from './roomResponseDto';
export * from './roomResponseDtoChoices';
export * from './roomResponseDtoCurrentUserRole';
export * from './roomResponseDtoUserRoles';
export * from './roomsControllerChooseMovieBody';
export * from './roomsControllerCreateRoom201';
export * from './roomsControllerGetChatHistory200';
export * from './roomsControllerGetChatHistory200MessagesItem';
export * from './roomsControllerLeaveRoomBody';
export * from './roomsControllerMuteUserBody';
export * from './roomsControllerMuteUserBodyDurationMinutes';
export * from './updateAgeRatingDto';
export * from './updateAwardCategoryDto';
export * from './updateAwardDto';
export * from './updateContentTypeDto';
export * from './updateCountryDto';
export * from './updateGenreDto';
export * from './userProfileResponseDto';
export * from './userProfileResponseDtoRole';
export * from './userResponseDto';
export * from './userResponseDtoAvatarUrl';
export * from './userResponseDtoEmail';
export * from './userResponseDtoName';
export * from './userResponseDtoRole';
export * from './usersControllerGetAllUsersParams';
export * from './usersControllerUpdateNameBody';