/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Match-movie example
 * The Match-Movie API description
 * OpenAPI spec version: 1.0
 */

export type MatchControllerCheckStatusBody = {
  /** The ID of the user */
  userId: number;
  /**
   * Client-generated key for this deck-round check
   * @maxLength 128
   */
  idempotencyKey?: string;
};
