/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Match-movie example
 * The Match-Movie API description
 * OpenAPI spec version: 1.0
 */
import type { Rating } from './rating';

/**
 * Рейтинг фильма
 * @nullable
 */
export type MovieRating = Rating | null;
