/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Match-movie example
 * The Match-Movie API description
 * OpenAPI spec version: 1.0
 */
import type { MoviePoster } from './moviePoster';
import type { MovieBackdrop } from './movieBackdrop';
import type { Genre } from './genre';
import type { Country } from './country';
import type { ReleaseYear } from './releaseYear';
import type { MovieRating } from './movieRating';
import type { MovieVotes } from './movieVotes';

export interface Movie {
  /** ID фильма */
  id: number;
  /**
   * Название фильма
   * @nullable
   */
  name: string | null;
  /**
   * Альтернативное название фильма
   * @nullable
   */
  alternativeName: string | null;
  /**
   * Английское название фильма
   * @nullable
   */
  enName: string | null;
  /** Тип фильма */
  type: string;
  /** Номер типа */
  typeNumber: number;
  /**
   * Год выпуска
   * @nullable
   */
  year: number | null;
  /**
   * Описание фильма
   * @nullable
   */
  description: string | null;
  /**
   * Короткое описание фильма
   * @nullable
   */
  shortDescription: string | null;
  /**
   * Статус фильма
   * @nullable
   */
  status: string | null;
  /**
   * Длина фильма
   * @nullable
   */
  movieLength: number | null;
  /**
   * Общая длина сериала
   * @nullable
   */
  totalSeriesLength: number | null;
  /**
   * Длина серии
   * @nullable
   */
  seriesLength: number | null;
  /**
   * Возрастной рейтинг
   * @nullable
   */
  ageRating: number | null;
  /**
   * Постер фильма
   * @nullable
   */
  poster: MoviePoster;
  /**
   * Задний план фильма
   * @nullable
   */
  backdrop: MovieBackdrop;
  /** Жанры фильма */
  genres: Genre[];
  /** Страны производства */
  countries: Country[];
  /**
   * Годы выпуска
   * @nullable
   */
  releaseYears: ReleaseYear[] | null;
  /**
   * Рейтинг фильма
   * @nullable
   */
  rating: MovieRating;
  /**
   * Голоса
   * @nullable
   */
  votes: MovieVotes;
  /**
   * Популярность в топ-10
   * @nullable
   */
  top10: number | null;
  /**
   * Популярность в топ-250
   * @nullable
   */
  top250: number | null;
  /**
   * Доступность билетов
   * @nullable
   */
  ticketsOnSale: boolean | null;
  /** Является ли сериалом */
  isSeries: boolean;
}
