/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Match-movie example
 * The Match-Movie API description
 * OpenAPI spec version: 1.0
 */
import type { MyFeedbackMessageResponseStatus } from './myFeedbackMessageResponseStatus';
import type { FeedbackUserMessagePayload } from './feedbackUserMessagePayload';
import type { MyFeedbackMessageResponseReply } from './myFeedbackMessageResponseReply';

export interface MyFeedbackMessageResponse {
  id: number;
  email: string;
  text: string;
  status: MyFeedbackMessageResponseStatus;
  /** @nullable */
  adminReply: string | null;
  /** @nullable */
  adminRepliedAt: string | null;
  createdAt: string;
  updatedAt: string;
  user: FeedbackUserMessagePayload;
  /** @nullable */
  reply: MyFeedbackMessageResponseReply;
}
