/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Match-movie example
 * The Match-Movie API description
 * OpenAPI spec version: 1.0
 */

export interface Poster {
  /** URL постера */
  url: string;
  /**
   * URL превью постера
   * @nullable
   */
  previewUrl: string | null;
}
