/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Match-movie example
 * The Match-Movie API description
 * OpenAPI spec version: 1.0
 */

export interface ReleaseYear {
  /**
   * Начало выпуска
   * @nullable
   */
  start: number | null;
  /**
   * Конец выпуска
   * @nullable
   */
  end: number | null;
}
