/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Match-movie example
 * The Match-Movie API description
 * OpenAPI spec version: 1.0
 */

export type RoomStateDtoMatchPhase = typeof RoomStateDtoMatchPhase[keyof typeof RoomStateDtoMatchPhase];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RoomStateDtoMatchPhase = {
  LOBBY: 'LOBBY',
  SWIPING: 'SWIPING',
  WAITING_ROUND: 'WAITING_ROUND',
  FINAL_PICK: 'FINAL_PICK',
} as const;
