/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Match-movie example
 * The Match-Movie API description
 * OpenAPI spec version: 1.0
 */

export type RoomStateDtoRoomStatus = typeof RoomStateDtoRoomStatus[keyof typeof RoomStateDtoRoomStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RoomStateDtoRoomStatus = {
  PENDING: 'PENDING',
  SET: 'SET',
  EXCEPTION: 'EXCEPTION',
} as const;
