/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Match-movie example
 * The Match-Movie API description
 * OpenAPI spec version: 1.0
 */
import type { RoomStateDtoMatchPhase } from './roomStateDtoMatchPhase';
import type { RoomStateDtoRoomStatus } from './roomStateDtoRoomStatus';
import type { RoomParticipantStateDto } from './roomParticipantStateDto';
import type { RoomDeckSummaryDto } from './roomDeckSummaryDto';

export interface RoomStateDto {
  roomKey: string;
  roomId: string;
  matchPhase: RoomStateDtoMatchPhase;
  roomStatus: RoomStateDtoRoomStatus;
  /** Monotonic; bump on deck / critical room changes */
  aggregateVersion: number;
  participants: RoomParticipantStateDto[];
  deck: RoomDeckSummaryDto;
  /** Whether room has saved filters JSON */
  hasFilters: boolean;
  /** Echo for stale snapshot detection on client */
  serverTime?: string;
}
