/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * MM Admin API
 * API documentation for MM Admin backend. All endpoints use JWT authentication via HTTP-only cookies or Bearer token in Authorization header.

## WebSocket Chat API

Chat functionality is available via WebSocket connections. See [WebSocket Chat Documentation](./websocket-chat.md) for details.

### Quick Reference:
- **Connection:** 
  - Development: `ws://localhost:4000/rooms`
  - Production with proxy: Use relative URL `/rooms` or `/socket.io/` (Socket.IO will auto-detect protocol)
  - Production direct: `wss://your-backend-server/rooms` (⚠️ MUST use `wss://` for HTTPS sites)
- **Important:** 
  - For HTTPS frontends (like `https://dashboard.moviematch.space`), you MUST use `wss://` protocol, not `ws://`
  - If using proxy (Next.js rewrites), use relative URL: `/rooms` or let Socket.IO auto-detect
  - Socket.IO client will automatically use `wss://` if page is loaded over HTTPS
- **Authentication:** JWT token in cookie or Authorization header
- **Events:**
  - `sendMessage` - Send a chat message
  - `chatHistory` - Receive chat history (auto-sent on room join)
  - `newMessage` - Receive new messages from other users
  - `error` - Error notifications

### Chat Message Format:
```json
{
  "roomId": "uuid",
  "message": "Your message text (1-1000 characters)"
}
```

### Requirements:
- User must be authenticated
- User must be a member of the room
- Messages are limited to 1000 characters
- Chat history is automatically sent when joining a room (up to 100 messages)

 * OpenAPI spec version: 1.0
 */
import type { RoomResponseDtoUserRoles } from './roomResponseDtoUserRoles';
import type { RoomResponseDtoChoices } from './roomResponseDtoChoices';
import type { RoomResponseDtoCurrentUserRole } from './roomResponseDtoCurrentUserRole';

export interface RoomResponseDto {
  /** Room ID (UUID) */
  roomId: string;
  /** Public room code (6 digits) */
  publicCode: string;
  /**
   * User ID of the room creator (UUID)
   * @nullable
   */
  createdBy?: string | null;
  /** List of user IDs in the room */
  users: string[];
  /** User roles in the room (userId -> role) */
  userRoles: RoomResponseDtoUserRoles;
  /** User choices (userId -> movieId) */
  choices: RoomResponseDtoChoices;
  /** Is current user a member of this room */
  isMember?: boolean;
  /** Is current user the creator of this room */
  isCreator?: boolean;
  /** Can current user manage the room (creator or admin). Use this field to determine if user can delete the room. */
  canManage?: boolean;
  /** Current user's role in the room */
  currentUserRole?: RoomResponseDtoCurrentUserRole;
  /** Is current user muted in this room */
  isMuted?: boolean;
  /** When mute expires (timestamp in milliseconds) */
  muteExpiresAt?: number;
  /** Room creation timestamp */
  createdAt?: number;
  /** Room last update timestamp */
  updatedAt?: number;
}
