/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Match-movie example
 * The Match-Movie API description
 * OpenAPI spec version: 1.0
 */

/**
 * Status of the user
 */
export type UpdateUserStatusDtoUserStatus = typeof UpdateUserStatusDtoUserStatus[keyof typeof UpdateUserStatusDtoUserStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateUserStatusDtoUserStatus = {
  ACTIVE: 'ACTIVE',
  WAITING: 'WAITING',
  CLOSED: 'CLOSED',
} as const;
