/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Match-movie example
 * The Match-Movie API description
 * OpenAPI spec version: 1.0
 */

export type UpdateUserNsiDtoClient = typeof UpdateUserNsiDtoClient[keyof typeof UpdateUserNsiDtoClient];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateUserNsiDtoClient = {
  GOOGLE: 'GOOGLE',
  NONE: 'NONE',
} as const;
