/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Match-movie example
 * The Match-Movie API description
 * OpenAPI spec version: 1.0
 */

export interface UpdateAwardCategoryDto {
  name?: string;
  slug?: string;
  /** ID премии (напр. Оскар) */
  awardId?: number;
  description?: string;
  keywords?: string[];
}
