/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Match-movie example
 * The Match-Movie API description
 * OpenAPI spec version: 1.0
 */
import type { ClientType } from './clientType';

export interface UpdateUserNsiDto {
  username?: string;
  email?: string;
  /** @minLength 8 */
  password?: string;
  client?: ClientType;
}
