/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Match-movie example
 * The Match-Movie API description
 * OpenAPI spec version: 1.0
 */
import type { UserNsiResponseDto } from './userNsiResponseDto';

export interface UsersNsiPageResponseDto {
  page: number;
  limit: number;
  total: number;
  items: UserNsiResponseDto[];
}
