/**
 * Generated by orval v7.13.2 🍺 — extended manually for admin user filters.
 * Match-movie example
 */
export type UsersNsiControllerGetUsersParams = {
  /**
   * @minimum 1
   */
  page?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * Case-insensitive partial match on email
   */
  emailQuery?: string;
  /**
   * Case-insensitive partial match on username
   */
  usernameQuery?: string;
  lifecycle?: 'all' | 'new' | 'returning';
  createdFrom?: string;
  createdTo?: string;
  lastLoginFrom?: string;
  lastLoginTo?: string;
  platform?: string;
  /**
   * id|createdAt|lastLoginAt + :asc|:desc
   */
  sort?: string;
};
