/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Match-movie example
 * The Match-Movie API description
 * OpenAPI spec version: 1.0
 */

export type UserRoomMembershipDtoRole = typeof UserRoomMembershipDtoRole[keyof typeof UserRoomMembershipDtoRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserRoomMembershipDtoRole = {
  admin: 'admin',
  participant: 'participant',
} as const;
