/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Match-movie example
 * The Match-Movie API description
 * OpenAPI spec version: 1.0
 */
import type { UserNsiResponseDtoClient } from './userNsiResponseDtoClient';

export interface UserNsiResponseDto {
  id: number;
  username: string;
  email: string;
  client: UserNsiResponseDtoClient;
  /**
   * Registration timestamp
   * @nullable
   */
  createdAt?: string | null;
  /**
   * Last successful sign-in (password or Google)
   * @nullable
   */
  lastLoginAt: string | null;
  /**
   * Client platform from last login (e.g. web)
   * @nullable
   */
  platform: string | null;
}
