/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Match-movie example
 * The Match-Movie API description
 * OpenAPI spec version: 1.0
 */

export interface Votes {
  /**
   * Голоса KP
   * @nullable
   */
  kp: number | null;
  /**
   * Голоса IMDB
   * @nullable
   */
  imdb: number | null;
  /**
   * Голоса кинокритиков
   * @nullable
   */
  filmCritics: number | null;
  /**
   * Голоса российских кинокритиков
   * @nullable
   */
  russianFilmCritics: number | null;
  /**
   * Ожидание голосов
   * @nullable
   */
  await: number | null;
}
