/**
 * NSI Admin API models (preserved from MM Admin OpenAPI).
 * Not regenerated by orval — see src/app/core/api/nsi-admin/.
 */

export * from './ageRatingControllerGetInfiniteParams';
export * from './ageRatingControllerGetWithPagesParams';
export * from './ageRatingControllerSendProgress200';
export * from './ageRatingControllerSendProgress200Data';
export * from './ageRatingPaginationResponseDto';
export * from './awardCategoryControllerGetInfiniteParams';
export * from './awardCategoryControllerGetWithPagesParams';
export * from './awardCategoryControllerSendProgress200';
export * from './awardCategoryControllerSendProgress200Data';
export * from './awardPaginationResponseDto';
export * from './awardSearchParamsDto';
export * from './awardsControllerGetInfiniteParams';
export * from './awardsControllerGetWithPagesParams';
export * from './awardsControllerSendProgress200';
export * from './awardsControllerSendProgress200Data';
export * from './contentTypeControllerGetInfiniteParams';
export * from './contentTypeControllerGetWithPagesParams';
export * from './contentTypeControllerSendProgress200';
export * from './contentTypeControllerSendProgress200Data';
export * from './contentTypePaginationResponseDto';
export * from './contentTypeSearchParamsDto';
export * from './countriesControllerGetInfiniteParams';
export * from './countriesControllerGetWithPagesParams';
export * from './countriesControllerSendProgress200';
export * from './countriesControllerSendProgress200Data';
export * from './countriesPaginationResponseDto';
export * from './createAgeRatingDto';
export * from './createAwardCategoryDto';
export * from './createAwardDto';
export * from './createContentTypeDto';
export * from './createCountryDto';
export * from './createGenreDto';
export * from './fileUploadDto';
export * from './genrePaginationResponseDto';
export * from './genresControllerGetInfiniteParams';
export * from './genresControllerGetWithPagesParams';
export * from './genresControllerSendProgress200';
export * from './genresControllerSendProgress200Data';
export * from './getAgeRatingByIdDto';
export * from './getAwardByIdDto';
export * from './getAwardCategoryByIdDto';
export * from './getContentTypeByIdDto';
export * from './getCountryByIdDto';
export * from './getGenreByIdDto';
export * from './idParamDto';
export * from './updateAgeRatingDto';
export * from './updateAwardCategoryDto';
export * from './updateAwardDto';
export * from './updateContentTypeDto';
export * from './updateCountryDto';
export * from './updateGenreDto';
